### ISSUE TITLE
建议增加评论功能

### ISSUE THREAD

**Issue by zzh1996** [Smart-Hypercube/0x01.me#1]
并且迁移以前的评论！

**Comment by ghost** [comment]
已增加评论功能，原来很简单啊，在多说注册一下，然后把注册的信息加到站点配置文件里就好了。因为使用的模板已经自带了对多说的支持

**Comment by ghost** [comment]
基本上迁移好了，但迁移来的和真正的还是有一定区别，不打算努力了

**Comment by SmartHypercube** [comment]
Workaround:
If we wait long enough, the Earth will eventually be consumed by the Sun.
